/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Thu Apr 04 12:15:42 GMT 2024
 */

package com.example;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class EvosuiteYeah_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.example.EvosuiteYeah"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "Cp1252"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\123\\AppData\\Local\\Temp\\"); 
    java.lang.System.setProperty("user.country", "US"); 
    java.lang.System.setProperty("user.dir", "E:\\UOW\\Software Testing and Analysis\\Evosuite Specific 2\\demo"); 
    java.lang.System.setProperty("user.home", "C:\\Users\\123"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "123"); 
    java.lang.System.setProperty("user.timezone", "Australia/Sydney"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(EvosuiteYeah_ESTest_scaffolding.class.getClassLoader() ,
      "j2html.tags.specialized.OutputTag",
      "j2html.tags.specialized.OptgroupTag",
      "j2html.tags.attributes.IOnresize",
      "j2html.tags.attributes.IOntimeupdate",
      "j2html.tags.specialized.BodyTag",
      "j2html.tags.specialized.TextareaTag",
      "j2html.tags.attributes.IDownload",
      "j2html.tags.specialized.TitleTag",
      "j2html.tags.specialized.TrTag",
      "j2html.tags.attributes.IHreflang",
      "j2html.tags.attributes.ISrc",
      "j2html.tags.attributes.IAutofocus",
      "j2html.tags.attributes.ISrcset",
      "j2html.tags.specialized.SelectTag",
      "j2html.tags.specialized.DatalistTag",
      "j2html.tags.specialized.BrTag",
      "j2html.rendering.FlatHtml",
      "j2html.tags.attributes.IAutoplay",
      "j2html.tags.attributes.ISelected",
      "j2html.tags.specialized.SupTag",
      "j2html.tags.specialized.DialogTag",
      "j2html.tags.attributes.ILabel",
      "j2html.tags.attributes.ISrclang",
      "j2html.tags.attributes.IHref",
      "j2html.tags.specialized.TfootTag",
      "j2html.tags.attributes.IValue",
      "j2html.tags.attributes.IOptimum",
      "j2html.tags.attributes.IOnoffline",
      "j2html.utils.EmptySelectorBodyException",
      "j2html.tags.attributes.IHeaders",
      "j2html.tags.specialized.AbbrTag",
      "j2html.tags.attributes.IMethod",
      "j2html.tags.specialized.H4Tag",
      "j2html.tags.specialized.MainTag",
      "j2html.tags.attributes.IStep",
      "j2html.tags.attributes.IForm",
      "j2html.tags.UnescapedText",
      "j2html.tags.specialized.PTag",
      "j2html.tags.specialized.DataTag",
      "j2html.tags.specialized.MarkTag",
      "j2html.tags.attributes.IWidth",
      "j2html.tags.attributes.IAction",
      "j2html.tags.attributes.IOnerror",
      "j2html.tags.specialized.UTag",
      "j2html.utils.UnterminatedCommentException",
      "j2html.tags.specialized.RpTag",
      "j2html.tags.attributes.ICols",
      "j2html.tags.specialized.MenuitemTag",
      "j2html.tags.specialized.TheadTag",
      "j2html.tags.attributes.IOnpopstate",
      "j2html.tags.specialized.SourceTag",
      "j2html.tags.specialized.AudioTag",
      "j2html.tags.attributes.ILow",
      "j2html.tags.specialized.DelTag",
      "j2html.tags.attributes.IAccept",
      "j2html.tags.attributes.IOnloadedmetadata",
      "j2html.tags.specialized.TimeTag",
      "j2html.tags.attributes.IName",
      "j2html.tags.attributes.IEnctype",
      "j2html.tags.Renderable",
      "j2html.tags.specialized.BaseTag",
      "j2html.tags.attributes.IHeight",
      "j2html.tags.attributes.IMax",
      "j2html.tags.specialized.StyleTag",
      "j2html.tags.attributes.IOnreset",
      "j2html.tags.attributes.IOnprogress",
      "j2html.tags.specialized.OlTag",
      "j2html.tags.specialized.FigureTag",
      "j2html.tags.attributes.INovalidate",
      "j2html.tags.specialized.FooterTag",
      "j2html.tags.specialized.ArticleTag",
      "j2html.tags.attributes.IPreload",
      "j2html.tags.attributes.ILoop",
      "j2html.tags.attributes.ISizes",
      "j2html.tags.attributes.IOnbeforeunload",
      "j2html.tags.specialized.DetailsTag",
      "j2html.tags.ContainerTag",
      "j2html.tags.attributes.IOnended",
      "j2html.tags.specialized.DdTag",
      "j2html.tags.attributes.IList",
      "j2html.tags.attributes.IOntoggle",
      "j2html.tags.attributes.IOnloadeddata",
      "j2html.tags.specialized.HrTag",
      "j2html.rendering.FlatHtml$FlatTagBuilder",
      "j2html.tags.specialized.DtTag",
      "j2html.tags.attributes.IRequired",
      "j2html.tags.specialized.UlTag",
      "j2html.tags.attributes.IOnloadstart",
      "j2html.tags.specialized.VarTag",
      "j2html.tags.specialized.H3Tag",
      "j2html.tags.specialized.KeygenTag",
      "j2html.tags.specialized.ScriptTag",
      "j2html.tags.specialized.RubyTag",
      "j2html.tags.attributes.IOnonline",
      "j2html.tags.specialized.ATag",
      "j2html.tags.specialized.SectionTag",
      "j2html.utils.Indenter",
      "j2html.tags.attributes.IOpen",
      "j2html.tags.attributes.IAutocomplete",
      "j2html.tags.attributes.IMaxlength",
      "j2html.tags.specialized.DfnTag",
      "j2html.tags.attributes.IColspan",
      "j2html.tags.specialized.ButtonTag",
      "j2html.tags.specialized.ImgTag",
      "j2html.tags.attributes.IAlt",
      "j2html.tags.attributes.IOnpause",
      "j2html.tags.specialized.VideoTag",
      "j2html.tags.attributes.IOnsearch",
      "j2html.rendering.TagBuilder",
      "j2html.tags.specialized.HeadTag",
      "j2html.utils.TextEscaper",
      "j2html.tags.specialized.InputTag",
      "j2html.tags.specialized.InsTag",
      "j2html.tags.attributes.IFormaction",
      "j2html.tags.specialized.CaptionTag",
      "j2html.tags.attributes.IContent",
      "j2html.tags.attributes.IOnplaying",
      "j2html.tags.specialized.CanvasTag",
      "j2html.tags.specialized.ProgressTag",
      "j2html.tags.specialized.TableTag",
      "j2html.tags.specialized.QTag",
      "j2html.tags.specialized.RtTag",
      "j2html.tags.specialized.MapTag",
      "j2html.tags.attributes.IScope",
      "j2html.tags.attributes.IReversed",
      "j2html.utils.UnbalancedBracesException",
      "j2html.tags.attributes.IWrap",
      "j2html.utils.JSMin$UnterminatedCommentException",
      "j2html.tags.attributes.IOnwaiting",
      "j2html.tags.attributes.IStart",
      "j2html.tags.specialized.ParamTag",
      "j2html.tags.specialized.SubTag",
      "j2html.tags.specialized.PictureTag",
      "j2html.tags.Tag",
      "j2html.tags.specialized.AsideTag",
      "j2html.tags.specialized.DivTag",
      "j2html.rendering.HtmlBuilder",
      "j2html.tags.attributes.IChecked",
      "j2html.tags.attributes.IMedia",
      "j2html.tags.specialized.TrackTag",
      "j2html.tags.specialized.CodeTag",
      "j2html.tags.attributes.ISize",
      "j2html.tags.attributes.IUsemap",
      "j2html.tags.specialized.AreaTag",
      "j2html.tags.specialized.SampTag",
      "j2html.tags.specialized.FigcaptionTag",
      "j2html.tags.EmptyTag",
      "j2html.tags.specialized.ColTag",
      "j2html.TagCreator",
      "j2html.tags.attributes.IRowspan",
      "j2html.tags.specialized.H2Tag",
      "j2html.utils.Minifier",
      "j2html.tags.attributes.ICharset",
      "j2html.tags.specialized.MetaTag",
      "j2html.utils.JSMin$UnterminatedStringLiteralException",
      "j2html.tags.specialized.TdTag",
      "j2html.tags.specialized.BTag",
      "j2html.tags.attributes.IOnhashchange",
      "j2html.tags.attributes.IOnstalled",
      "j2html.tags.attributes.IDisabled",
      "j2html.tags.attributes.IOnsubmit",
      "j2html.tags.attributes.IDefer",
      "j2html.tags.specialized.ColgroupTag",
      "j2html.tags.attributes.IOncuechange",
      "j2html.tags.attributes.IOncanplaythrough",
      "j2html.tags.attributes.IOnvolumechanged",
      "j2html.tags.attributes.ISandbox",
      "j2html.tags.specialized.FormTag",
      "j2html.tags.specialized.WbrTag",
      "j2html.tags.attributes.IOnabort",
      "j2html.attributes.Attr",
      "j2html.tags.specialized.PreTag",
      "j2html.tags.attributes.IOnseeked",
      "j2html.tags.specialized.TbodyTag",
      "j2html.tags.specialized.LegendTag",
      "j2html.tags.specialized.LabelTag",
      "j2html.tags.specialized.SlotTag",
      "j2html.tags.specialized.LiTag",
      "j2html.tags.specialized.CiteTag",
      "j2html.tags.specialized.IframeTag",
      "j2html.tags.specialized.BdiTag",
      "j2html.tags.Text",
      "j2html.tags.attributes.IDatetime",
      "j2html.attributes.Attribute",
      "j2html.tags.specialized.HtmlTag",
      "j2html.tags.attributes.IOnratechange",
      "j2html.tags.attributes.IPlaceholder",
      "j2html.utils.UnterminatedSelectorException",
      "j2html.tags.attributes.IRows",
      "j2html.tags.specialized.NoscriptTag",
      "j2html.tags.specialized.AddressTag",
      "j2html.tags.attributes.ISrcdoc",
      "j2html.tags.specialized.KbdTag",
      "j2html.tags.specialized.H1Tag",
      "j2html.tags.attributes.ICoords",
      "j2html.tags.attributes.IPoster",
      "j2html.tags.specialized.H6Tag",
      "j2html.tags.attributes.IMuted",
      "j2html.tags.attributes.IOnplay",
      "j2html.tags.IInstance",
      "j2html.tags.specialized.TemplateTag",
      "j2html.tags.attributes.IMin",
      "j2html.tags.specialized.EmTag",
      "j2html.tags.attributes.IOnstorage",
      "j2html.tags.specialized.SummaryTag",
      "j2html.tags.attributes.IOndurationchange",
      "j2html.tags.attributes.IReadonly",
      "j2html.tags.specialized.SpanTag",
      "j2html.tags.specialized.NavTag",
      "j2html.tags.attributes.IData",
      "j2html.tags.specialized.STag",
      "j2html.tags.specialized.StrongTag",
      "j2html.tags.specialized.LinkTag",
      "j2html.tags.attributes.IOnafterprint",
      "j2html.tags.specialized.ThTag",
      "j2html.tags.specialized.SmallTag",
      "j2html.tags.attributes.IPattern",
      "com.example.EvosuiteYeah",
      "j2html.utils.JSMin$UnterminatedRegExpLiteralException",
      "j2html.Config",
      "j2html.tags.attributes.IHigh",
      "j2html.utils.CSSMin",
      "j2html.tags.specialized.HeaderTag",
      "j2html.tags.attributes.IKind",
      "j2html.tags.specialized.BdoTag",
      "j2html.tags.attributes.IShape",
      "j2html.tags.specialized.EmbedTag",
      "j2html.tags.specialized.DlTag",
      "j2html.tags.specialized.ObjectTag",
      "j2html.tags.attributes.IAsync",
      "j2html.tags.specialized.MeterTag",
      "j2html.tags.attributes.IOnbeforeprint",
      "j2html.tags.attributes.IOnpagehide",
      "j2html.tags.specialized.MenuTag",
      "j2html.tags.attributes.IIsmap",
      "j2html.tags.attributes.IOnload",
      "j2html.tags.attributes.IRel",
      "j2html.tags.attributes.ISpan",
      "j2html.tags.specialized.OptionTag",
      "j2html.tags.specialized.FieldsetTag",
      "j2html.tags.attributes.IDefault",
      "j2html.utils.EscapeUtil",
      "j2html.tags.attributes.IType",
      "j2html.tags.attributes.IOnunload",
      "j2html.tags.specialized.H5Tag",
      "j2html.tags.attributes.IMultiple",
      "j2html.tags.attributes.IDirname",
      "j2html.tags.attributes.IOnseeking",
      "j2html.tags.specialized.BlockquoteTag",
      "j2html.attributes.Attr$ShortForm",
      "j2html.tags.DomContent",
      "j2html.tags.specialized.ITag",
      "j2html.tags.attributes.IOnpageshow",
      "j2html.tags.attributes.ICite",
      "j2html.tags.attributes.ITarget",
      "j2html.tags.attributes.IOnemptied",
      "j2html.tags.attributes.IFor",
      "j2html.utils.JSMin",
      "j2html.tags.attributes.IControls",
      "j2html.tags.attributes.IOncanplay",
      "j2html.tags.attributes.IOnsuspend"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(EvosuiteYeah_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "com.example.EvosuiteYeah",
      "j2html.TagCreator",
      "j2html.tags.DomContent",
      "j2html.tags.Tag",
      "j2html.tags.ContainerTag",
      "j2html.tags.specialized.NavTag",
      "j2html.tags.Text",
      "j2html.Config",
      "j2html.rendering.FlatHtml",
      "j2html.rendering.FlatHtml$FlatTagBuilder",
      "j2html.utils.EscapeUtil",
      "j2html.tags.specialized.SectionTag",
      "j2html.tags.specialized.BodyTag",
      "j2html.tags.specialized.PTag",
      "j2html.tags.specialized.PreTag",
      "j2html.attributes.Attr",
      "j2html.attributes.Attr$ShortForm",
      "j2html.attributes.Attribute",
      "j2html.tags.specialized.ArticleTag",
      "j2html.tags.specialized.BlockquoteTag",
      "j2html.tags.specialized.H2Tag",
      "j2html.tags.specialized.LabelTag",
      "j2html.tags.specialized.SubTag",
      "j2html.tags.specialized.ButtonTag",
      "j2html.tags.specialized.TextareaTag",
      "j2html.tags.specialized.DetailsTag",
      "j2html.tags.specialized.OptionTag",
      "j2html.tags.EmptyTag",
      "j2html.tags.specialized.InputTag",
      "j2html.tags.specialized.FormTag",
      "j2html.tags.specialized.StyleTag",
      "j2html.tags.UnescapedText",
      "j2html.tags.specialized.ThTag",
      "j2html.tags.specialized.TrTag",
      "j2html.tags.specialized.TableTag",
      "j2html.tags.specialized.ImgTag",
      "j2html.tags.specialized.DivTag",
      "j2html.tags.specialized.H3Tag",
      "j2html.tags.specialized.StrongTag",
      "j2html.tags.specialized.MainTag",
      "j2html.tags.specialized.HeaderTag",
      "j2html.tags.specialized.TitleTag",
      "j2html.tags.specialized.SmallTag",
      "j2html.tags.specialized.AsideTag",
      "j2html.tags.specialized.FooterTag",
      "j2html.tags.specialized.LiTag",
      "j2html.tags.specialized.UlTag",
      "j2html.tags.specialized.HeadTag",
      "j2html.tags.specialized.SupTag",
      "j2html.tags.specialized.H4Tag",
      "j2html.tags.specialized.CodeTag",
      "j2html.tags.specialized.H5Tag",
      "j2html.tags.specialized.DialogTag",
      "j2html.tags.specialized.HtmlTag",
      "j2html.tags.specialized.DelTag",
      "j2html.tags.specialized.ATag",
      "j2html.tags.specialized.TdTag",
      "j2html.tags.specialized.FigcaptionTag",
      "j2html.tags.specialized.LinkTag",
      "j2html.tags.specialized.CiteTag",
      "j2html.tags.specialized.SpanTag",
      "j2html.tags.specialized.H1Tag"
    );
  }
}
