/*
 * This file was automatically generated by EvoSuite
 * Sun May 19 00:26:58 GMT 2024
 */

package com.example;

import org.junit.Test;
import static org.junit.Assert.*;
import com.example.J2HTMLConversion;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class J2HTMLConversion_ESTest extends J2HTMLConversion_ESTest_scaffolding {

    // these generated test cases were copied and pasted back to the original project
    // evertime it generates test cases. (Read the comment in J2HTMLConversion.java file first)

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      J2HTMLConversion j2HTMLConversion0 = new J2HTMLConversion();
      String string0 = j2HTMLConversion0.test_case_264();
      assertEquals("<p><cite>The Scream</cite> by Edvard Munch. Painted in 1893.</p>", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      J2HTMLConversion j2HTMLConversion0 = new J2HTMLConversion();
      String string0 = j2HTMLConversion0.test_case_286();
      assertEquals("<strong style=\"color:grey;padding-left:5px;\">Important text</strong>", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      J2HTMLConversion j2HTMLConversion0 = new J2HTMLConversion();
      String string0 = j2HTMLConversion0.test_case_269();
      assertEquals("<wbr class=\"theClassWBR 2\" draggable=\"true\">", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      J2HTMLConversion j2HTMLConversion0 = new J2HTMLConversion();
      String string0 = j2HTMLConversion0.test_case_281();
      assertEquals("<code class=\"code-class\">System.out.println(&quot;Hello, world!&quot;);</code>", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      J2HTMLConversion j2HTMLConversion0 = new J2HTMLConversion();
      String string0 = j2HTMLConversion0.test_case_290();
      assertEquals("<p class=\"p-class1\">The check</p>", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      J2HTMLConversion j2HTMLConversion0 = new J2HTMLConversion();
      String string0 = j2HTMLConversion0.test_case_299();
      assertEquals("<track src=\"subtitles_en.vtt\" kind=\"subtitles\" label=\"English\">", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      J2HTMLConversion j2HTMLConversion0 = new J2HTMLConversion();
      String string0 = j2HTMLConversion0.test_case_294();
      assertEquals("<output id=\"result\" style=\"color:green;border:2px solid black\"></output>", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      J2HTMLConversion j2HTMLConversion0 = new J2HTMLConversion();
      String string0 = j2HTMLConversion0.test_case_277();
      assertEquals("<span style=\"color: red;\"><b>Bold text</b><br><i>Italic text</i></span>", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      J2HTMLConversion j2HTMLConversion0 = new J2HTMLConversion();
      String string0 = j2HTMLConversion0.test_case_272();
      assertEquals("<input type=\"text\" id=\"username\" name=\"username\" placeholder=\"Enter username\">", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      J2HTMLConversion j2HTMLConversion0 = new J2HTMLConversion();
      String string0 = j2HTMLConversion0.test_case_255();
      assertEquals("<input type=\"email\" id=\"email\" name=\"email\" placeholder=\"Enter your email address\" required>", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      J2HTMLConversion j2HTMLConversion0 = new J2HTMLConversion();
      String string0 = j2HTMLConversion0.test_case_263();
      assertEquals("<abbr class=\"theAbbr\">The abbr text</abbr>", string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      J2HTMLConversion j2HTMLConversion0 = new J2HTMLConversion();
      String string0 = j2HTMLConversion0.test_case_291();
      assertEquals("<progress value=\"70\" max=\"100\" class=\"progress-class\"></progress>", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      J2HTMLConversion j2HTMLConversion0 = new J2HTMLConversion();
      String string0 = j2HTMLConversion0.test_case_280();
      assertEquals("<blockquote><p>This is a quote.</p><p>Author: John Doe</p></blockquote>", string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      J2HTMLConversion j2HTMLConversion0 = new J2HTMLConversion();
      String string0 = j2HTMLConversion0.test_case_259();
      assertEquals("<body><h1 style=\"background-color:powderblue;\">This is a heading</h1><p style=\"background-color:tomato;\">This is a paragraph.</p></body>", string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      J2HTMLConversion j2HTMLConversion0 = new J2HTMLConversion();
      String string0 = j2HTMLConversion0.test_case_287();
      assertEquals("<section><h2>Section Title</h2><p>This is a section of content.</p></section>", string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      J2HTMLConversion j2HTMLConversion0 = new J2HTMLConversion();
      String string0 = j2HTMLConversion0.test_case_260();
      assertEquals("<em>This text is emphasized</em>", string0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      J2HTMLConversion j2HTMLConversion0 = new J2HTMLConversion();
      String string0 = j2HTMLConversion0.test_case_282();
      assertEquals("<iframe src=\"https://www.example.com\" width=\"800\" height=\"600\" class=\"iFrame\"></iframe>", string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      J2HTMLConversion j2HTMLConversion0 = new J2HTMLConversion();
      String string0 = j2HTMLConversion0.test_case_265();
      assertEquals("<cite class=\"theU\" style=\"padding-top:5px;\">The cite stuff</cite>", string0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      J2HTMLConversion j2HTMLConversion0 = new J2HTMLConversion();
      String string0 = j2HTMLConversion0.test_case_276();
      assertEquals("<textarea id=\"text\" rows=\"4\" cols=\"50\">Enter your text here</textarea>", string0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      J2HTMLConversion j2HTMLConversion0 = new J2HTMLConversion();
      String string0 = j2HTMLConversion0.test_case_271();
      assertEquals("<div class=\"container highlight\" style=\"color: blue;\"><p>This is inside a div tag.</p><span>This is inside a span tag.</span></div>", string0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      J2HTMLConversion j2HTMLConversion0 = new J2HTMLConversion();
      String string0 = j2HTMLConversion0.test_case_254();
      assertEquals("<html><head><title>The title checkup</title></head></html>", string0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      J2HTMLConversion j2HTMLConversion0 = new J2HTMLConversion();
      String string0 = j2HTMLConversion0.test_case_293();
      assertEquals("<figure><img src=\"image.jpg\" alt=\"Image\"><figcaption>A beautiful image</figcaption></figure>", string0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      J2HTMLConversion j2HTMLConversion0 = new J2HTMLConversion();
      String string0 = j2HTMLConversion0.test_case_298();
      assertEquals("<kbd style=\"color:red;\">Ctrl + C</kbd>", string0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      J2HTMLConversion j2HTMLConversion0 = new J2HTMLConversion();
      String string0 = j2HTMLConversion0.test_case_275();
      assertEquals("<button id=\"btn\" onclick=\"alert(&#x27;Button clicked!&#x27;)\">Click me</button>", string0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      J2HTMLConversion j2HTMLConversion0 = new J2HTMLConversion();
      String string0 = j2HTMLConversion0.test_case_270();
      assertEquals("<data style=\"color:darkblue;display:flex;\" dir=\"theSampleDir\">The data</data>", string0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      J2HTMLConversion j2HTMLConversion0 = new J2HTMLConversion();
      String string0 = j2HTMLConversion0.test_case_292();
      assertEquals("<details><summary>Click to expand</summary><p>Additional content goes here.</p></details>", string0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      J2HTMLConversion j2HTMLConversion0 = new J2HTMLConversion();
      String string0 = j2HTMLConversion0.test_case_253();
      assertEquals("<div class=\"menu-element active\"></div>", string0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      J2HTMLConversion j2HTMLConversion0 = new J2HTMLConversion();
      String string0 = j2HTMLConversion0.test_case_297();
      assertEquals("<samp id=\"samp-id-1\">Sample output</samp>", string0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      J2HTMLConversion j2HTMLConversion0 = new J2HTMLConversion();
      String string0 = j2HTMLConversion0.test_case_261();
      assertEquals("<body><div id=\"employees\"><div class=\"employee\"><h2>Rusira</h2><img src=\"The image path\"><p>Mr</p></div></div></body>", string0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      J2HTMLConversion j2HTMLConversion0 = new J2HTMLConversion();
      String string0 = j2HTMLConversion0.test_case_258();
      assertEquals("<a href=\"https://www.w3schools.com/html/\">Visit our HTML tutorial</a>", string0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      J2HTMLConversion j2HTMLConversion0 = new J2HTMLConversion();
      String string0 = j2HTMLConversion0.test_case_283();
      assertEquals("<meta charset=\"UTF-8\">", string0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      J2HTMLConversion j2HTMLConversion0 = new J2HTMLConversion();
      String string0 = j2HTMLConversion0.test_case_288();
      assertEquals("<aside><h3>Related Links</h3><ul><li><a href=\"#\" target=\"_blank\">Link 1</a></li><li><a href=\"#\">Link 2</a></li><li><a href=\"#\">Link 3</a></li></ul></aside>", string0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      J2HTMLConversion j2HTMLConversion0 = new J2HTMLConversion();
      String string0 = j2HTMLConversion0.test_case_266();
      assertEquals("<bdo dir=\"rtl\">This text will be written from right to left</bdo>", string0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      J2HTMLConversion j2HTMLConversion0 = new J2HTMLConversion();
      String string0 = j2HTMLConversion0.test_case_257();
      assertEquals("<img src=\"img_girl.jpg\" width=\"500\" height=\"600\">", string0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      J2HTMLConversion j2HTMLConversion0 = new J2HTMLConversion();
      String string0 = j2HTMLConversion0.test_case_252();
      assertEquals("<div class=\"menu-element active\"></div>", string0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      J2HTMLConversion j2HTMLConversion0 = new J2HTMLConversion();
      String string0 = j2HTMLConversion0.test_case_274();
      assertEquals("<table><tr><th>Name</th><th>Age</th></tr><tr><td>John</td><td>30</td></tr><tr><td>Jane</td><td>25</td></tr></table>", string0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      J2HTMLConversion j2HTMLConversion0 = new J2HTMLConversion();
      String string0 = j2HTMLConversion0.test_case_285();
      assertEquals("<nav><a href=\"/home\">Home</a><a href=\"/about\">About</a><a href=\"/contact\">Contact</a></nav>", string0);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      J2HTMLConversion j2HTMLConversion0 = new J2HTMLConversion();
      String string0 = j2HTMLConversion0.test_case_296();
      assertEquals("<rt>\u304B\u3093</rt>", string0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      J2HTMLConversion j2HTMLConversion0 = new J2HTMLConversion();
      String string0 = j2HTMLConversion0.test_case_268();
      assertEquals("<fieldset hidden>The field-text</fieldset>", string0);
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      J2HTMLConversion j2HTMLConversion0 = new J2HTMLConversion();
      String string0 = j2HTMLConversion0.test_case_279();
      assertEquals("<label for=\"nameInput\" style=\"width:2px;color:blue;\">Enter your name:</label>", string0);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      J2HTMLConversion j2HTMLConversion0 = new J2HTMLConversion();
      String string0 = j2HTMLConversion0.test_case_256();
      assertEquals("<input type=\"password\" id=\"password\" name=\"password\" placeholder=\"Enter your password\" required>", string0);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      J2HTMLConversion j2HTMLConversion0 = new J2HTMLConversion();
      String string0 = j2HTMLConversion0.test_case_267();
      assertEquals("<html><body><img style=\"padding-top:10px;padding-left:5px;\"></body></html>", string0);
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      J2HTMLConversion j2HTMLConversion0 = new J2HTMLConversion();
      String string0 = j2HTMLConversion0.test_case_278();
      assertEquals("<hr style=\"width:2px;color:blue;\">", string0);
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      J2HTMLConversion j2HTMLConversion0 = new J2HTMLConversion();
      String string0 = j2HTMLConversion0.test_case_289();
      assertEquals("<abbr title=\"HyperText Markup Language\">HTML</abbr>", string0);
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      J2HTMLConversion j2HTMLConversion0 = new J2HTMLConversion();
      String string0 = j2HTMLConversion0.test_case_262();
      assertEquals("<address><p>Written by John Doe.</p><p>Visit us at:</p><p>Example.com</p><p>Box 564, Disneyland</p><p>USA</p></address>", string0);
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      J2HTMLConversion j2HTMLConversion0 = new J2HTMLConversion();
      String string0 = j2HTMLConversion0.test_case_251();
      assertEquals("<p>This paragraph has <b>bold</b> and <i>italic</i> text.</p>", string0);
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      J2HTMLConversion j2HTMLConversion0 = new J2HTMLConversion();
      String string0 = j2HTMLConversion0.test_case_295();
      assertEquals("<time datetime=\"2024-04-10\">2024-04-10</time>", string0);
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      J2HTMLConversion j2HTMLConversion0 = new J2HTMLConversion();
      String string0 = j2HTMLConversion0.test_case_284();
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      J2HTMLConversion j2HTMLConversion0 = new J2HTMLConversion();
      String string0 = j2HTMLConversion0.test_case_273();
      assertEquals("<select name=\"options\"><option value=\"1\">Option 1</option><option value=\"2\" selected>Option 2</option><option value=\"3\">Option 3</option></select>", string0);
  }
}
